#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
导出 DeepConvNet 权重为 int8 量化 C 头文件
用法: python3 export_deepnet_weights.py
"""

import sys, os, gzip, struct, pickle
import numpy as np
from deep_convnet import DeepConvNet

def load_mnist_images(filename):
    with gzip.open(filename, 'rb') as f:
        magic = struct.unpack('>I', f.read(4))[0]
        n_images = struct.unpack('>I', f.read(4))[0]
        n_rows = struct.unpack('>I', f.read(4))[0]
        n_cols = struct.unpack('>I', f.read(4))[0]
        data = np.frombuffer(f.read(), dtype=np.uint8)
        return data.reshape(n_images, 1, n_rows, n_cols).astype(np.float64) / 255.0

def load_mnist_labels(filename):
    with gzip.open(filename, 'rb') as f:
        magic = struct.unpack('>I', f.read(4))[0]
        n_labels = struct.unpack('>I', f.read(4))[0]
        return np.frombuffer(f.read(), dtype=np.uint8)

def quantize_int8(arr):
    """对称量化到 int8, 返回量化值和scale"""
    max_val = np.max(np.abs(arr))
    if max_val == 0:
        max_val = 1.0
    scale = max_val / 127.0
    q = np.clip(np.round(arr / scale), -128, 127).astype(np.int8)
    return q, scale

def quantize_bias(b, W_scale, input_scale):
    """量化偏置: b_q = b / (W_scale * input_scale)"""
    combined_scale = W_scale * input_scale
    if combined_scale == 0:
        combined_scale = 1.0
    q = np.clip(np.round(b / combined_scale), -2**31, 2**31-1).astype(np.int32)
    return q

def export_deepnet_weights():
    """导出DeepConvNet权重"""
    # 加载模型
    network = DeepConvNet()
    network.load_params('deep_convnet_params.pkl')

    # 层定义
    layers = [
        ('W1', 'b1', 16, 1, 3, 3, 1, 1),   # Conv1: 16x1x3x3, stride=1, pad=1
        ('W2', 'b2', 16, 16, 3, 3, 1, 1),  # Conv2: 16x16x3x3, stride=1, pad=1
        ('W3', 'b3', 32, 16, 3, 3, 1, 1),  # Conv3: 32x16x3x3, stride=1, pad=1
        ('W4', 'b4', 32, 32, 3, 3, 1, 2),  # Conv4: 32x32x3x3, stride=1, pad=2
        ('W5', 'b5', 64, 32, 3, 3, 1, 1),  # Conv5: 64x32x3x3, stride=1, pad=1
        ('W6', 'b6', 64, 64, 3, 3, 1, 1),  # Conv6: 64x64x3x3, stride=1, pad=1
        ('W7', 'b7', 50, 1024, 0, 0, 0, 0), # Affine1: 1024->50
        ('W8', 'b8', 10, 50, 0, 0, 0, 0),   # Affine2: 50->10
    ]

    # 量化权重
    quantized = {}
    scales = {}
    for w_name, b_name, out_ch, in_ch, kh, kw, stride, pad in layers:
        W = network.params[w_name]
        b = network.params[b_name]

        # Conv层需要reshape为[out_ch, in_ch*kh*kw]
        # Affine层需要转置为[out_ch, in_ch]
        if kh > 0:
            W = W.reshape(out_ch, -1)
        else:
            W = W.T  # 转置: [in_ch, out_ch] -> [out_ch, in_ch]

        qW, sW = quantize_int8(W)
        quantized[w_name] = qW
        scales[w_name] = sW

        # 偏置使用简化量化: b_q = b / W_scale (假设input_scale=1)
        qb = quantize_bias(b, sW, 1.0)
        quantized[b_name] = qb
        scales[b_name] = sW  # 偏置scale与权重相同

    # 写入C头文件
    with open('deepnet_weights.h', 'w') as f:
        f.write("// Auto-generated by export_deepnet_weights.py\n")
        f.write("#ifndef DEEPNET_WEIGHTS_H\n#define DEEPNET_WEIGHTS_H\n\n")
        f.write("#include <stdint.h>\n\n")

        # 写入层配置
        f.write("// Layer configurations\n")
        f.write("// Conv layers: [out_channels][in_channels * kH * kW]\n")
        f.write("// Affine layers: [out_features][in_features]\n\n")

        # Conv1: W1[16][1*3*3] = W1[16][9]
        qW = quantized['W1']
        f.write(f"// Conv1: 16 filters, 1 input channel, 3x3, stride=1, pad=1\n")
        f.write(f"static const int8_t conv1_W[{16}][{1*3*3}] = {{\n")
        for i in range(16):
            vals = ', '.join(str(int(qW[i][j])) for j in range(1*3*3))
            f.write(f"  {{{vals}}},\n")
        f.write("};\n")
        vals = ', '.join(str(int(quantized['b1'][i])) for i in range(16))
        f.write(f"static const int32_t conv1_b[{16}] = {{{vals}}};\n\n")

        # Conv2: W2[16][16*3*3] = W2[16][144]
        qW = quantized['W2']
        f.write(f"// Conv2: 16 filters, 16 input channels, 3x3, stride=1, pad=1\n")
        f.write(f"static const int8_t conv2_W[{16}][{16*3*3}] = {{\n")
        for i in range(16):
            vals = ', '.join(str(int(qW[i][j])) for j in range(16*3*3))
            f.write(f"  {{{vals}}},\n")
        f.write("};\n")
        vals = ', '.join(str(int(quantized['b2'][i])) for i in range(16))
        f.write(f"static const int32_t conv2_b[{16}] = {{{vals}}};\n\n")

        # Conv3: W3[32][16*3*3] = W3[32][144]
        qW = quantized['W3']
        f.write(f"// Conv3: 32 filters, 16 input channels, 3x3, stride=1, pad=1\n")
        f.write(f"static const int8_t conv3_W[{32}][{16*3*3}] = {{\n")
        for i in range(32):
            vals = ', '.join(str(int(qW[i][j])) for j in range(16*3*3))
            f.write(f"  {{{vals}}},\n")
        f.write("};\n")
        vals = ', '.join(str(int(quantized['b3'][i])) for i in range(32))
        f.write(f"static const int32_t conv3_b[{32}] = {{{vals}}};\n\n")

        # Conv4: W4[32][32*3*3] = W4[32][288]
        qW = quantized['W4']
        f.write(f"// Conv4: 32 filters, 32 input channels, 3x3, stride=1, pad=2\n")
        f.write(f"static const int8_t conv4_W[{32}][{32*3*3}] = {{\n")
        for i in range(32):
            vals = ', '.join(str(int(qW[i][j])) for j in range(32*3*3))
            f.write(f"  {{{vals}}},\n")
        f.write("};\n")
        vals = ', '.join(str(int(quantized['b4'][i])) for i in range(32))
        f.write(f"static const int32_t conv4_b[{32}] = {{{vals}}};\n\n")

        # Conv5: W5[64][32*3*3] = W5[64][288]
        qW = quantized['W5']
        f.write(f"// Conv5: 64 filters, 32 input channels, 3x3, stride=1, pad=1\n")
        f.write(f"static const int8_t conv5_W[{64}][{32*3*3}] = {{\n")
        for i in range(64):
            vals = ', '.join(str(int(qW[i][j])) for j in range(32*3*3))
            f.write(f"  {{{vals}}},\n")
        f.write("};\n")
        vals = ', '.join(str(int(quantized['b5'][i])) for i in range(64))
        f.write(f"static const int32_t conv5_b[{64}] = {{{vals}}};\n\n")

        # Conv6: W6[64][64*3*3] = W6[64][576]
        qW = quantized['W6']
        f.write(f"// Conv6: 64 filters, 64 input channels, 3x3, stride=1, pad=1\n")
        f.write(f"static const int8_t conv6_W[{64}][{64*3*3}] = {{\n")
        for i in range(64):
            vals = ', '.join(str(int(qW[i][j])) for j in range(64*3*3))
            f.write(f"  {{{vals}}},\n")
        f.write("};\n")
        vals = ', '.join(str(int(quantized['b6'][i])) for i in range(64))
        f.write(f"static const int32_t conv6_b[{64}] = {{{vals}}};\n\n")

        # Affine1: W7[50][1024]
        qW = quantized['W7']
        f.write(f"// Affine1: 1024 -> 50\n")
        f.write(f"static const int8_t affine1_W[{50}][{1024}] = {{\n")
        for i in range(50):
            vals = ', '.join(str(int(qW[i][j])) for j in range(1024))
            f.write(f"  {{{vals}}},\n")
        f.write("};\n")
        vals = ', '.join(str(int(quantized['b7'][i])) for i in range(50))
        f.write(f"static const int32_t affine1_b[{50}] = {{{vals}}};\n\n")

        # Affine2: W8[10][50]
        qW = quantized['W8']
        f.write(f"// Affine2: 50 -> 10\n")
        f.write(f"static const int8_t affine2_W[{10}][{50}] = {{\n")
        for i in range(10):
            vals = ', '.join(str(int(qW[i][j])) for j in range(50))
            f.write(f"  {{{vals}}},\n")
        f.write("};\n")
        vals = ', '.join(str(int(quantized['b8'][i])) for i in range(10))
        f.write(f"static const int32_t affine2_b[{10}] = {{{vals}}};\n\n")

        # 量化scale
        f.write("// Quantization scales\n")
        for w_name in ['W1','W2','W3','W4','W5','W6','W7','W8']:
            f.write(f"static const float {w_name}_scale = {scales[w_name]:.10f}f;\n")
        f.write("\n#endif\n")

    # 打印统计
    total_bytes = sum(quantized[k].nbytes for k in quantized)
    print(f"deepnet_weights.h written, total weight size: {total_bytes} bytes ({total_bytes/1024:.1f} KB)")

    # 验证
    print("\nVerifying on test set...")
    dataset_dir = os.path.join(os.path.dirname(__file__), 'dataset')
    x_test = load_mnist_images(os.path.join(dataset_dir, 't10k-images-idx3-ubyte.gz'))
    t_test = load_mnist_labels(os.path.join(dataset_dir, 't10k-labels-idx1-ubyte.gz'))

    # 测试前100张
    correct = 0
    total = 100
    for i in range(total):
        y = network.predict(x_test[i:i+1], train_flg=False)
        pred = np.argmax(y)
        if pred == t_test[i]:
            correct += 1
    print(f"Python accuracy (first {total}): {correct}/{total}")

if __name__ == '__main__':
    export_deepnet_weights()
